
# global gene expression analysis

# loading libraries

```{r}
require(dplyr)
require(ggrepel)
require(ggplot2)
require(Matrix)
```

```{r}
file.copy('../../preprocess/generate_single_cell_data/alldata_pseudobulkpresence.Rds', 'alldata_pseudobulkpresence.Rds')
human_gene_expression.df <- readRDS('alldata_pseudobulkpresence.Rds')
cutoff.int <- attributes(human_gene_expression.df)$cutoff.int
file.remove('alldata_pseudobulkpresence.Rds')
```
```{r}
file.copy('../../preprocess/generate_single_cell_data/glycogene_mouse_panglaodb_pseudobulkpresence.Rds', 'glycogene_mouse_panglaodb_pseudobulkpresence.Rds')
mouse_gene_expression.df <- readRDS('glycogene_mouse_panglaodb_pseudobulkpresence.Rds')
cutoff.int <- attributes(mouse_gene_expression.df)$cutoff.int
file.remove('glycogene_mouse_panglaodb_pseudobulkpresence.Rds')
```


```{r}
# filtering for clusters of adequate size, annotation, and expression ----
filtering <- function(gene_expression.df, taxon_id = c('9606', '10090'), glycogenes_only = F, other_genes = NULL, gte200 = T, annotated = T) {

  # filtering out non glycogenes ---
  if(glycogenes_only) {
    genes.vec <- switch(
      taxon_id,
      '9606' = c(readLines('9606_glycogenes.txt'), other_genes),
      '10090' = c(readLines('10090_glycogenes.txt'), other_genes))
    gene_expression.df <- gene_expression.df[with(
      gene_expression.df, gene %in% genes.vec),]
  }

  # filtering out clusters with less than 200 cells ----
  gene_expression.df <-
    if(gte200) {
      gene_expression.df[with(
        gene_expression.df,
        cellnum >= 200),]
    } else { gene_expression.df }

  # filtering out clusters with unknown celltype annotation ----
  gene_expression.df <-
    if(isTRUE(annotated)) {
      gene_expression.df <- gene_expression.df[with(
        gene_expression.df,
        !(grepl(':Unknown', cluster))),]
    } else if(isFALSE(annotated)) {
      gene_expression.df <- gene_expression.df[with(
        gene_expression.df,
        grepl(':Unknown', cluster)),]
    } else { gene_expression.df }

  return(gene_expression.df)

}
```

```{r}
human_gene_expression.df <- filtering(human_gene_expression.df, taxon_id = '9606', glycogenes_only = T, other_genes = 'DAG1', gte200 = T, annotated = T)[,c('cluster','gene','cellnum','pseudobulk','status5E-03')]
```

```{r}
mouse_gene_expression.df <- filtering(mouse_gene_expression.df, taxon_id = '10090', glycogenes_only = T, other_genes = 'Dag1', gte200 = T, annotated = T)[,c('cluster','gene','cellnum','pseudobulk','status5E-03')]
```

```{r}
prediction.df_wrapper <- function(gene_expression.df, p_cutoff, numcells = 200, tissue = NA) {

  prediction.df <- if(is.na(tissue)) {
    gene_expression.df[with(
      gene_expression.df,
      cellnum >= numcells),
      c('cluster','cellnum','gene', p_cutoff)]
  } else {
    gene_expression.df[with(
      gene_expression.df,
      cellnum >= numcells &
        grepl(paste0(tissue,':.*$'), cluster)),
      c('cluster','cellnum','gene', p_cutoff)]
  }

  prediction.df$cluster <- paste0(prediction.df$cluster, ':', prediction.df$cellnum)
  prediction.df$cellnum <- NULL
  prediction.df <- reshape2::dcast(
    data = prediction.df,
    formula = gene ~ cluster,
    value.var = p_cutoff)
  rownames(prediction.df) <- prediction.df$gene
  prediction.df$gene <- NULL

  cluster_prediction.df <- data.frame(
    cellnum = as.integer(gsub('^.*:','',colnames(prediction.df))),
    num_unpredictable = colSums(prediction.df == 'unpredictable'),
    num_expressed = colSums(prediction.df == 'expressed'),
    num_unexpressed = colSums(prediction.df == 'unexpressed'))
  cluster_prediction.df$bucket_unpredictable <- cut(
    cluster_prediction.df$num_unpredictable,
    breaks = seq(-11,231,22),
    labels = paste0(seq(0,100,10),'%'))
  cluster_prediction.df$bucket_numcell <- cut(
    cluster_prediction.df$cellnum,
    breaks = c(seq(100, 900, 100), seq(1000, 6000, 1000)))

  global_prediction.df <- data.frame(
    gene = rownames(prediction.df),
    percent_unpredictable = rowSums(prediction.df == 'unpredictable')/ncol(prediction.df),
    percent_predictable =  1 - rowSums(prediction.df == 'unpredictable')/ncol(prediction.df),
    percent_unexpressed = rowSums(prediction.df == 'unexpressed')/ncol(prediction.df),
    percent_expressed = rowSums(prediction.df == 'expressed')/ncol(prediction.df))
  global_prediction.df$bucket_unpredictable_0.1 <- cut(
    x = global_prediction.df$percent_unpredictable,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))
  global_prediction.df$bucket_unexpressed_0.1 <- cut(
    x = global_prediction.df$percent_unexpressed,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))
  global_prediction.df$bucket_expressed_0.1 <- cut(
    x = global_prediction.df$percent_expressed,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))


  global_prediction.df$status    <- p_cutoff
  cluster_prediction.df$status   <- p_cutoff

  global_prediction.df$minclust  <- numcells
  cluster_prediction.df$minclust <- numcells

  if(!is.na(tissue)) {
    global_prediction.df$tissue  <- tissue
    global_prediction.df$nclust  <- ncol(prediction.df)
    cluster_prediction.df$tissue <- tissue }

  result.list <- list(
    prediction.df = prediction.df,
    cluster_prediction.df = cluster_prediction.df,
    global_prediction.df = global_prediction.df)

  return(result.list)

}
```

# bucketing expression predictions

```{r}
human_global_prediction.df <- prediction.df_wrapper(human_gene_expression.df, p_cutoff = 'status5E-03')$global_prediction.df
mouse_global_prediction.df <- prediction.df_wrapper(mouse_gene_expression.df, p_cutoff = 'status5E-03')$global_prediction.df
```

# percent of GTs predicted in some percent of cells

```{r}
data.df = data.frame(pct_cell = rep(seq(0.00, 1, 0.01), 2))
data.df = within(data.df, {
  pct_gt = c(
    sapply(pct_cell[1:101], function(pct) {
      sum(human_global_prediction.df$percent_expressed >= pct)/length(human_global_prediction.df$gene) }),
    sapply(pct_cell[1:101], function(pct) {
      sum(mouse_global_prediction.df$percent_expressed >= pct)/length(mouse_global_prediction.df$gene) }))
  dataset = rep(c('TS', 'PM'), each = 101)
})
```

# SupplementaryFigure5B

```{r, fig.width=7, fig.height=7}

qplot(
  data = data.df,
  x = pct_cell,
  y = pct_gt,
  color = dataset,
  geom = 'line',
  main = 'percent of GTs predicted as expressed in at least some percent of cells',
  xlab = '% of cells',
  ylab = '% of genes') +
  scale_x_continuous(breaks = seq(0,1,0.1)) +
  scale_y_continuous(breaks = seq(0,1,0.1)) +
  theme_bw()
```
