
```{r include=FALSE}
library(edgeR)
library(compositions)
library(recount)
library(biomaRt)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(cowplot)
library(readxl)
library(colorspace)
```

#TODO read in tissue_results_all

```{r echo=FALSE}
sc_seg_rel_diff.df <- readRDS('sc_seg_rel_diff_df.Rds')

wanted_sets = grep('agg',sc_seg_rel_diff.df$source,value=T)

sc_seg_rel_diff.df <- sc_seg_rel_diff.df[with(
  sc_seg_rel_diff.df,
  source %in% wanted_sets &
  gene %in% unique(tissue_results_all$gene)),]
```

```{r}
pseudobulk_rel_diff = readRDS('pseudobulk_log_seg_norm.Rds')
message("Loading up Pseudobulks from ",attributes(pseudobulk_rel_diff)$repo," revision ",attributes(pseudobulk_rel_diff)$revision)
pseudobulk_rel_diff$is_unknown= grepl('Unknown',pseudobulk_rel_diff$tissue)
cutoffs=attributes(pseudobulk_rel_diff)$cutoffs
median_cutoff=median(cutoffs)
```

```{r}
single_cell_to_bulk_plot = function(gene) {
  
  main_data = tissue_results_all[
    tissue_results_all$gene == gene &          # explicitly filtering for gene
      tissue_results_all$ref_gene == 'all' &   # explicitly filtering for quants normalised by all segs
      tissue_results_all$samples > 10 &        # explicitly filtering for tissue with greater than 10 samples
      tissue_results_all$log_cpm > log(1.05),] # explicitly filtering for sample with TPM > 0.05
  
  secondary_data = sc_seg_rel_diff.df[sc_seg_rel_diff.df$gene == gene,]
  pseudobulk_data = pseudobulk_rel_diff[pseudobulk_rel_diff$gene == gene,]
  pseudobulk_data_mouse_known = subset(pseudobulk_data, source == 'mouse' & !is_unknown)
  pseudobulk_data_mouse_unknown = subset(pseudobulk_data, source == 'mouse' & is_unknown)
  pseudobulk_data_human_known = subset(pseudobulk_data, source == 'human' & !is_unknown)
  pseudobulk_data_human_unknown = subset(pseudobulk_data, source == 'human' & is_unknown)

  boxplot_data = main_data[
    main_data$log_cpm > log(2) &
    main_data$source == 'gtex',
    'rel_diff',
    drop = F]

  boxplot_data = if(nrow(boxplot_data) == 0) {
    rbind.data.frame(boxplot_data, data.frame(rel_diff = -10)) # hack
  } else { boxplot_data }

  box_plot =
    ggplot(boxplot_data) +
    stat_summary(
      fun.data = function(x) {
        setNames(
          quantile(x, probs = c(0.10, 0.25, 0.5, 0.75, 0.90)),
          c("ymin", "lower", "middle", "upper", "ymax"))
      },
      aes(y = rel_diff, x = 0),
      geom = "boxplot") +
    scale_y_continuous(
      limits = c(-6, 6),
      breaks = seq(-6, 6, by = 2)) +
    coord_flip() +
    theme_minimal() +
    theme(
      legend.position = 'none',
      axis.title.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      plot.margin = unit(c(0,0,0,0), "cm"))
  
  bulk_plot = 
    ggplot(main_data) +
    geom_vline(xintercept = 0, color = 'black') +
    geom_histogram(
      aes(x = rel_diff, fill = paste(ifelse(log_cpm > log(2), 'expressed', 'unexpressed'), source)),
      binwidth = 0.25,
      stat = "bin") +
    scale_x_continuous(
      limits = c(-6, 6), 
      breaks = seq(-6, 6, by = 2),
      minor_breaks = seq(-5, 5, by = 2)) +
    scale_fill_manual(
      values = c(
        'expressed gtex' = '#555555',
        'expressed tcga' = '#999999',
        'unexpressed gtex' = '#69968077',
        'unexpressed tcga' = '#c8d9d177',
        mouse = 'blue',
        human = 'red'))
  
  bulk_plot.df = ggplot_build(bulk_plot)$data[[2]]
  max_count = with(bulk_plot.df, max(aggregate.data.frame(x = list(sum = count), by = list(x = x), FUN = sum)$sum))
  
  bulk_plot = bulk_plot +
    scale_y_continuous(
      breaks = seq.default(0, max_count, length.out = 5)) +
    annotate(
      geom = 'label',
      x = -6,
      y = max_count,
      label = max_count,
      size = 2) +
    theme_minimal() +
    theme(
      legend.position = 'none',
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x= element_blank(),
      plot.margin = unit(c(0, 0, 0, 0), "cm"))

  sc_plot =
    ggplot(secondary_data) +
    geom_vline(xintercept = 0, color = 'black') +
    geom_vline(xintercept = median_cutoff, color = 'black') +
    geom_area(
      data = pseudobulk_data_mouse_known,
      aes(x = rel_diff, y = after_stat(density), fill = paste(source, is_unknown)),
      stat = "bin",
      binwidth = 0.25,
      alpha = 0.25) +
    geom_area(
      data = pseudobulk_data_mouse_unknown,
      aes(x = rel_diff, y = after_stat(density), fill = paste(source, is_unknown)),
      stat = "bin",
      binwidth = 0.25,
      alpha = 0.25)+
    geom_area(
      data = pseudobulk_data_human_known,
      aes(x = rel_diff, y = after_stat(density), fill = paste(source, is_unknown)),
      stat = "bin",
      binwidth = 0.25,
      alpha = 0.25) +
    geom_area(
      data = pseudobulk_data_human_unknown,
      aes(x = rel_diff, y = after_stat(density), fill = paste(source, is_unknown)),
      stat = "bin",
      binwidth = 0.25,
      alpha = 0.25)+
    geom_density(
      aes(x = rel_diff, y = after_stat(density)),
      colour = "#555555",
      binwidth = 0.25)+
    scale_x_continuous(
      limits = c(-6, 6),
      breaks = seq(-6, 6, by = 2),
      minor_breaks = seq(-5, 5, by = 2),
      labels = c('-6', '', '', '0', '', '', '6')) +
    scale_fill_manual(
      values=c(
        "mouse TRUE" = 'blue',
        "mouse FALSE" = 'darkblue',
        "human TRUE" = 'red',
        "human FALSE" = "darkred"))

  max_density <- max(plyr::rbind.fill(ggplot_build(sc_plot)$data[c(3,4,5,7)])$density, na.rm = T)

  sc_plot = sc_plot +
    scale_y_continuous(
      breaks = seq.default(0, max_density, length.out = 5)) +
    annotate(
      geom = 'label',
      x = -6,
      y = max_density,
      label = round(max_density, digits = 2),
      size = 2) +
    theme_minimal() +
    theme(
      legend.position = 'none',
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank(),
      axis.text.x = element_text(size = 5, margin=margin(t=0)),
      panel.grid.minor.y = element_blank(),
      plot.margin = unit(c(0,0,0,0), "cm"))

  subplots = list(
    primary = box_plot,
    secondary = bulk_plot,
    tertiary = sc_plot)

  aligned = cowplot::plot_grid(
    plotlist=subplots,
    align='v',
    ncol=1,
    rel_heights=c(0.2,0.5,0.3))

  title = ggdraw() +
    cowplot::draw_label(
      gene, fontface = 'bold', x = 0.5, hjust = 0.5, size = 10) +
    theme(plot.margin = margin(t = 0, r = 0, b = 6, l = 0))

  iqr_info = ggdraw() +
    cowplot::draw_label(
      paste0('IQR:', round(iqr(main_data$rel_diff[main_data$log_cpm > log(2)]), digits = 2)),
      fontface = 'plain', x = 0.5, hjust = 0.5, size = 7) +
    theme(plot.margin = margin(t=0, r = 0, b = 6, l = 0))

  cowplot::plot_grid(
    iqr_info,aligned,title,
    ncol = 1,
    # rel_heights values control vertical title margins
    rel_heights = c(0.1,1,0.1))
}
```

```{r}
shared_lookup = 
  intersect(
    names(glycogene_lookup), 
    intersect(
        unique(pseudobulk_rel_diff$gene), 
        unique(subset(tissue_results_all, samples > 10 & log_cpm > log(1.05))$gene)))
```

# SupplementaryFigure3A

```{r full_histograms, fig.height=60, fig.width=30, warning=FALSE}
oldw = getOption("warn")
options(warn=-1)
gridobjs = gridExtra::arrangeGrob(grobs = lapply(shared_lookup, single_cell_to_bulk_plot), ncol=10)
options(warn=oldw)
grid::grid.draw(gridobjs)
```

