
# reading in human pseudobulk Rds files

```{r load_human_rds}
if(!file.exists("alldata_human.Rds")){
  rds = list.files(path = '../hsap_samples_tabuladb/', pattern = '.Rds.gz', recursive = T)
  raw_alldata = sapply(paste('../hsap_samples_tabuladb/', rds, sep = ''), function(x) { 
    y <- gzfile(x)
    z <- gzcon(y)
    data = readRDS(z)
    close(z)
    data })
}
```

# relabing human clusters

```{r relabel_human_rds}
if ('raw_alldata' %in% ls()) {
fixed = sapply(1:length(raw_alldata),function(x) {
  srs_names = sapply( sapply(rds,strsplit,'_'), function(x) grep('^SR',x,value=T) ,simplify = F)
  newids = dimnames(raw_alldata[[x]])[[1]]
  tissue = attributes(raw_alldata[[x]])$tissue
  if (length(unlist(srs_names)) > 0) {
    newids = paste(srs_names[[x]][2],tissue,dimnames(raw_alldata[[x]])[[1]],sep=':')
    if (length(newids) != length(attributes(raw_alldata[[x]])$clustersize)) {
      browser()
    }
  } else {
    newids = paste(tissue,newids,sep=':')
  }

  newids = paste(ifelse(attributes(raw_alldata[[x]])$clustersize < 200, 'SMALL_','' ),newids,sep='')
  dimnames(raw_alldata[[x]]) <- list(newids, dimnames(raw_alldata[[x]])[[2]])
  attributes(raw_alldata[[x]])$sizes <- setNames(attributes(raw_alldata[[x]])$clustersize,rownames(raw_alldata[[x]]))
  raw_alldata[[x]]
})
}
```

# concatenating Rds files

```{r concat_human_rds}
if ('fixed' %in% ls()) {
  alldata = do.call(function(...) {
    tmp <- plyr::rbind.fill.matrix(...)
    cols = dimnames(tmp)[[2]]
    rows <- sapply(fixed, function(i) {
      dimnames(i)[[1]]
    })
    dimnames(tmp) = list(unlist(rows),cols)
    return(tmp)

  }, fixed)
  sizes = do.call(c,lapply(fixed,function(set){ attributes(set)$sizes }))
  attributes(alldata)$clustersize = sizes
  rm(fixed)
  saveRDS(alldata,'alldata_human.Rds')
  rm(alldata)
}
```
