
```{r}
file.copy('../generate_single_cell_data/alldata_pseudobulkpresence.Rds', 'alldata_pseudobulkpresence.Rds')
gene_expression.df <- readRDS('alldata_pseudobulkpresence.Rds')
cutoff.int <- attributes(gene_expression.df)$cutoff.int
file.remove('alldata_pseudobulkpresence.Rds')
```

```{r}
# filtering for clusters of adequate size, annotation, and expression ----
filtering <- function(gene_expression.df, taxon_id = c('9606', '10090'), glycogenes_only = F, other_genes = NULL, gte200 = T, annotated = T) {
  
  # filtering out non glycogenes ---
  if(glycogenes_only) {
    genes.vec <- switch(
      taxon_id, 
      '9606' = c(readLines('9606_glycogenes.txt'), other_genes),
      '10090' = c(readLines('data/genesets/10090_glycogenes.txt'), other_genes))
    gene_expression.df <- gene_expression.df[with(
      gene_expression.df, gene %in% genes.vec),]
  }
  
  # filtering out clusters with less than 200 cells ----
  gene_expression.df <- 
    if(gte200) {
      gene_expression.df[with(
        gene_expression.df,
        cellnum >= 200),]
    } else { gene_expression.df }
  
  # filtering out clusters with unknown celltype annotation ----
  gene_expression.df <- 
    if(isTRUE(annotated)) {
      gene_expression.df <- gene_expression.df[with(
        gene_expression.df, 
        !(grepl(':Unknown', cluster))),]
    } else if(isFALSE(annotated)) {
      gene_expression.df <- gene_expression.df[with(
        gene_expression.df, 
        grepl(':Unknown', cluster)),]
    } else { gene_expression.df }
  
  return(gene_expression.df)

}
```

```{r}
gene_expression.df <- filtering(gene_expression.df, taxon_id = '9606', glycogenes_only = T, other_genes = 'DAG1', gte200 = T, annotated = T)
```

```{r}
prediction.df_wrapper <- function(gene_expression.df, p_cutoff, numcells = 200, tissue = NA) {
  
  prediction.df <- if(is.na(tissue)) { 
    gene_expression.df[with(
      gene_expression.df, 
      cellnum >= numcells), 
      c('cluster','cellnum','gene', p_cutoff)]
  } else {
    gene_expression.df[with(
      gene_expression.df, 
      cellnum >= numcells &
        grepl(paste0(tissue,':.*$'), cluster)), 
      c('cluster','cellnum','gene', p_cutoff)]
  }
  
  prediction.df$cluster <- paste0(prediction.df$cluster, ':', prediction.df$cellnum)
  prediction.df$cellnum <- NULL
  prediction.df <- reshape2::dcast(
    data = prediction.df, 
    formula = gene ~ cluster, 
    value.var = p_cutoff)
  rownames(prediction.df) <- prediction.df$gene
  prediction.df$gene <- NULL
  
  cluster_prediction.df <- data.frame(
    cellnum = as.integer(gsub('^.*:','',colnames(prediction.df))),
    num_unpredictable = colSums(prediction.df == 'unpredictable'),
    num_expressed = colSums(prediction.df == 'expressed'),
    num_unexpressed = colSums(prediction.df == 'unexpressed'))
  cluster_prediction.df$bucket_unpredictable <- cut(
    cluster_prediction.df$num_unpredictable,
    breaks = seq(-11,231,22),
    labels = paste0(seq(0,100,10),'%'))
  cluster_prediction.df$bucket_numcell <- cut(
    cluster_prediction.df$cellnum,
    breaks = c(seq(100, 900, 100), seq(1000, 6000, 1000)))
  
  global_prediction.df <- data.frame(
    gene = rownames(prediction.df),
    percent_unpredictable = rowSums(prediction.df == 'unpredictable')/ncol(prediction.df),
    percent_predictable =  1 - rowSums(prediction.df == 'unpredictable')/ncol(prediction.df),
    percent_unexpressed = rowSums(prediction.df == 'unexpressed')/ncol(prediction.df),
    percent_expressed = rowSums(prediction.df == 'expressed')/ncol(prediction.df))
  global_prediction.df$bucket_unpredictable_0.1 <- cut(
    x = global_prediction.df$percent_unpredictable,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))
  global_prediction.df$bucket_unexpressed_0.1 <- cut(
    x = global_prediction.df$percent_unexpressed,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))
  global_prediction.df$bucket_expressed_0.1 <- cut(
    x = global_prediction.df$percent_expressed,
    breaks = c(-0.05, 0, seq(0.05,1,0.1), 1, 1.05), # seq(-0.05,1.05,0.1),
    labels = paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')) # paste0(seq(0,100,10),'%'))
  
  
  global_prediction.df$status    <- p_cutoff
  cluster_prediction.df$status   <- p_cutoff
  
  global_prediction.df$minclust  <- numcells
  cluster_prediction.df$minclust <- numcells
  
  if(!is.na(tissue)) { 
    global_prediction.df$tissue  <- tissue
    global_prediction.df$nclust  <- ncol(prediction.df)
    cluster_prediction.df$tissue <- tissue }
  
  result.list <- list(
    prediction.df = prediction.df,
    cluster_prediction.df = cluster_prediction.df,
    global_prediction.df = global_prediction.df)
  
  return(result.list)
  
}
```

```{r}
# explicitly looking at global prediction status with cluster size ----
cluster_prediction.df <- prediction.df_wrapper(gene_expression.df, p_cutoff = 'status5E-03')[[2]]
```

```{r}
# explicitly looking at global prediction status with genes ----
global_prediction.df <- prediction.df_wrapper(gene_expression.df, p_cutoff = 'status5E-03')[[3]]
```

## SupplementaryFigure5A

```{r hist12, fig.width=7, fig.height=7}
## histogram of genes expressed in percent of total clusters (stacked by percent unexpressed)
hist12 <- function(pvalue, minsize = 200, tiss = NA) {
  
  require(ggplot2)
  
  overview <- if(is.na(tiss)) { 'global' } else { 'tissue' }
  switch(
    overview,
    'global' = {
      plot.df <- 
        global_prediction.df[with(
          global_prediction.df, 
          status == pvalue & 
            minclust == minsize),] 
      label.char <- paste0('number of genes expressed in percent of total clusters\nn = ', with(gene_expression.df, length(unique(cluster[cellnum >= 200]))))
      subtitle.char <- paste0('p-value<=', gsub('status', '', pvalue), '\ncluster>=200')
    },
    'tissue' =  { 
      plot.df <- 
        tissue_prediction.df[with(
          tissue_prediction.df, 
          status == pvalue & 
            minclust == minsize &
            tissue == tiss),] 
      label.char <- paste0('number of genes expressed in percent of total clusters\nn = ', unique(plot.df$nclust))
      subtitle.char <- paste0('tissue=', tiss, '\np-value<=', gsub('status', '', pvalue), '\ncluster>=200')
    })
  
  ggplot.obj <-
    ggplot(plot.df) + 
    geom_histogram(
      aes(x = percent_expressed, 
          fill = bucket_unexpressed_0.1,
          group = bucket_unexpressed_0.1),
      breaks = seq(-0.05, 1.05, 0.1)) +
    scale_fill_manual(
      values = setNames(
        c('grey', rev(RColorBrewer::brewer.pal(11, 'Spectral')), '#40366f'),
        paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%')),
      guide = guide_legend(
        title = 'percent\nunexpressed',
        reverse = T)) +
    scale_x_continuous(breaks = seq(0,1,0.1)) + 
    scale_y_continuous(breaks = seq(0,100,5)) +
    expand_limits(x = c(0,1)) +
    theme_bw() +
    theme(axis.text.x = element_text(colour = rev(RColorBrewer::brewer.pal(11, 'Spectral')))) +
    ggtitle(
      label = label.char,
      subtitle = subtitle.char)
  
  plot.df$x <- cut(
    plot.df$percent_expressed,
    breaks = seq(-0.05, 1.05, 0.1),
    labels = seq(0,1,0.1))
  plot.df$fill <- setNames(
    c('grey', rev(RColorBrewer::brewer.pal(11, 'Spectral')), '#40366f'), 
    paste0(c(0,5,10,20,30,40,50,60,70,80,90,95,100),'%'))[
      plot.df$bucket_unexpressed_0.1]
  
  ggplot.df <- ggplot_build(ggplot.obj)$data[[1]]
  text.df <- merge(ggplot.df, plot.df)[,c('x','y','ymin','ymax','fill','gene')]
  
  text.df <- do.call(
    rbind.data.frame, Filter(
      Negate(is.null), lapply(
        split(text.df, list(text.df$x, text.df$fill)), 
        function(text_subset.df) { 
          if(nrow(text_subset.df) == 0) { return(NULL) 
          } else { 
            text_subset.df <- text_subset.df[order(text_subset.df$gene, decreasing = T),]
            text_subset.df$y <- seq(
              unique(text_subset.df$ymin) + 0.5, 
              unique(text_subset.df$ymax) - 0.5, 
              length.out = nrow(text_subset.df)) 
            return(text_subset.df) } })))[, c('x','y','gene')]
  
  ggplot.obj <-
    ggplot.obj + 
    geom_text(
      data = text.df, 
      aes(x = x, y = y, label = gene), 
      size = 1) + 
    ylab('# of genes')
  
  return(ggplot.obj)
  
}
```

```{r, fig.width=7, fig.height=7}
hist12('status5E-03')
```
