
```{r include=FALSE}
library(edgeR)
library(compositions)
library(recount)
library(biomaRt)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(cowplot)
library(readxl)
library(colorspace)
```

```{r include=FALSE}
lookup_symbol = function(gene,genedata) {
  gene=paste('^',gene,sep='')
  rownames(subset(as.data.frame(rowData(genedata)),grepl(gene,symbol) & !grepl('-AS',symbol)))
}
```

```{r eval=file.exists('glycogene_lookup.Rds')}
glycogene_lookup=readRDS('glycogene_lookup.Rds')
```

```{r eval=!file.exists('glycogene_lookup.Rds')}
ensembl = useEnsembl(biomart = "ensembl",dataset = "hsapiens_gene_ensembl")
glycogene_lookup = with(
  getBM(
    attributes = c('hgnc_symbol','ensembl_gene_id'),
    filters = 'hgnc_symbol',
    values = read.delim('glycogenes.tsv',header = F)$V1,
    mart = ensembl), 
  setNames(ensembl_gene_id, hgnc_symbol))
saveRDS(glycogene_lookup,'glycogene_lookup.Rds')
remove(ensembl)
```

```{r eval=file.exists('seg_lookup.Rds')}
seg_lookup = readRDS('seg_lookup.Rds')
```

```{r eval=!file.exists('seg_lookup.Rds')}
seg_lookup <- 
  setNames(
      lapply(
        readxl::excel_sheets('pnas.1820006116.sd01.xlsx'), 
        readxl::read_xlsx, 
        path = 'pnas.1820006116.sd01.xlsx'),
      readxl::excel_sheets('pnas.1820006116.sd01.xlsx'))
seg_lookup = lapply(seg_lookup, as.data.frame)
seg_lookup = lapply(seg_lookup, `[[`, 1)
seg_lookup = lapply(seg_lookup, toupper)
seg_lookup = Reduce(intersect, seg_lookup)
ensembl = useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
seg_lookup = with(
  getBM(
    attributes=c('hgnc_symbol', 'ensembl_gene_id'), 
    filters = 'hgnc_symbol', 
    values = seg_lookup,
    mart = ensembl), 
  setNames(ensembl_gene_id, hgnc_symbol))
attributes(seg_lookup)$repo = "glycogenome_expression_variation"
attributes(seg_lookup)$revision = system("git describe --always --dirty", intern=T)
saveRDS(seg_lookup,'seg_lookup.Rds')
remove(ensembl)
```

```{r eval=file.exists('tissue_results_log_tcga.Rds')}
tissue_results_tcga = readRDS('tissue_results_log_tcga.Rds')
```

```{r eval=file.exists('tissue_results_log.Rds')}
tissue_results = readRDS('tissue_results_log.Rds')
```

```{r include=FALSE}
readTissueData = function(rse_gene,tissue,samples) {
  
  mtx = assay(rse_gene)[,samples]

  # We want to normalise the count data per tissue set
  y = DGEList(counts=mtx,group=rep('X',ncol(mtx)))
  y = calcNormFactors(y)
  # Apply the clr to smooth out the data a bit
  count_clr = apply(cpm(y),2,clr)
  count_log = apply(cpm(y)+1,2,log)
  
  rownames(count_log) = stringr::str_replace(rownames(count_log),'\\..*$','')
  rownames(count_clr) = rownames(count_log)

  gene_lookup = c(glycogene_lookup, seg_lookup)
  genes = count_log[intersect(rownames(count_log), gene_lookup),]
  glycogenes_clr = count_clr[intersect((rownames(count_clr)),gene_lookup),]
  reverse_genes = setNames(names(gene_lookup), gene_lookup)
  rownames(genes) = reverse_genes[rownames(genes)]
  rownames(glycogenes_clr) = rownames(genes)

  # We want to collect the mean clr, sd of the clr, IQR of the clr
  # This will give us the sets of fold-changes for genes that we expect to 
  # see within normal tissue function -> Envelope for cell-level change
  
  glycogenes = genes[intersect(rownames(genes), names(gene_lookup)),]
  glycogenes_clr = glycogenes_clr[intersect(rownames(genes), names(gene_lookup)),]
  
  genenames = rownames(glycogenes)
  
  data = reshape2:::melt.matrix(glycogenes, varnames = c('gene','sample_id'), value.name = 'log_cpm', as.is = T)

  ref_data = data[data$gene %in% names(seg_lookup),]
  ref_data = aggregate.data.frame(
    x = list(seg_geom_avg = ref_data$log_cpm), 
    by = list(sample_id = ref_data$sample_id), 
    FUN = function(x) { exp(mean(log(x))) })
  
  data = merge(data, ref_data, by = 'sample_id')
  
  data$rel_frac = data$log_cpm/data$seg_geom_avg
  data$rel_diff = data$log_cpm-data$seg_geom_avg
  data$seg_geom_avg <- NULL

  stats = data.frame(
    stddev = apply(glycogenes, 1, sd),
    iqr = apply(glycogenes, 1, iqr),
    mean_clr = apply(glycogenes_clr, 1, mean),
    samples = ncol(glycogenes),
    gene = genenames,
    ref_gene = 'all')
  
  stats = merge(data, stats, by = c('gene'))
  stats$tissue = tissue

  stats
}
```

```{r eval=!file.exists('tissue_results_log_tcga.Rds')}
load('TCGA/rse_gene.Rdata')

coldata = subset(colData(rse_gene),gdc_cases.samples.sample_type == 'Solid Tissue Normal')

# Group by tissue
all_tissues = unique(coldata[,'gdc_cases.project.primary_site'])

tissue_results_tcga = lapply(all_tissues, function(tissue) {
  samples = rownames(subset(coldata, gdc_cases.project.primary_site == tissue))
  if (length(samples) > 1) {
    readTissueData(rse_gene,tissue,samples)
  } else {
    return()
  }
})

tissue_results_tcga = do.call(rbind, tissue_results_tcga)

attributes(tissue_results_tcga)$repo = "glycogenome_expression_variation"
attributes(tissue_results_tcga)$revision = system("git describe --always --dirty", intern=T)
saveRDS(tissue_results_tcga,file = 'tissue_results_log_tcga.Rds')
```

```{r eval=!file.exists('tissue_results_log.Rds')}
load('SRP012682/rse_gene_new.Rdata')

# Group by tissue
all_tissues = unique(colData(rse_gene)[,'smts'])

tissue_results = lapply(all_tissues, function(tissue) {
  message(tissue)
  samples = rownames(subset(colData(rse_gene),smts == tissue))
  readTissueData(rse_gene,tissue,samples)
})

tissue_results = do.call(rbind, tissue_results)

attributes(tissue_results)$repo = "glycogenome_expression_variation"
attributes(tissue_results)$revision = system("git describe --always --dirty",intern=T)
saveRDS(tissue_results,file = 'tissue_results_log.Rds')
```

```{r}
tissue_results_all = rbind(
  cbind(tissue_results, source='gtex'),
  cbind(tissue_results_tcga, source='tcga'))
```
